[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['markdown', 'tsx', 'typescript', 'csv', 'dockerfile']
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
hook_add = '''
  let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'doums/darcula'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
  \'active': {
  \  'left': [ [ 'mode', 'paste' ], [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
  \  },
  \  'component_function': {
  \    'gitbranch': 'fugitive#head',
  \   },
  \ 'colorscheme': 'darculaOriginal'
  \ }
set laststatus=2
set noshowmode
'''

#coc系を入れてみる
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merge = 0
hook_add = '''
  source $XDG_CONFIG_HOME/nvim/coc.vim
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

#fzf asdfのものを使用する。
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

# which-key
[[plugins]]
repo = 'folke/which-key.nvim'
hook_add = '''
lua << EOF
  require("which-key").setup {
    -- your configuration comes here
    -- or leave it empty to use the default settings
    -- refer to the configuration section below
  }
EOF
'''

# TODO 設定できたらやりたい
# [[plugins]]
# repo = 'kdheepak/lazygit.nvim'

