[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['markdown', 'tsx', 'typescript', 'csv', 'dockerfile']
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
hook_add = '''
  let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'doums/darcula'

#coc系を入れてみる
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merge = 0
hook_add = '''
  source $XDG_CONFIG_HOME/nvim/coc.vim
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
  \'active': {
  \  'left': [ [ 'mode', 'paste' ], [ 'cocstatus', 'gitbranch', 'readonly', 'filename', 'modified' ] ]
  \  },
  \  'component_function': {
  \    'gitbranch': 'FugitiveHead',
  \    'cocstaus': 'coc#status'
  \   },
  \ 'colorscheme': 'darculaOriginal'
  \ }
set laststatus=2
set noshowmode
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
    nnoremap <silent><C-k> :Command<CR>
'''

# which-key
# ignore fzf.preview for no popup error when exec fzf.preview
[[plugins]]
repo = 'folke/which-key.nvim'
hook_add = '''
lua << EOF
  local wk = require("which-key")
  wk.register({
    ["[fzf-p]"] = {"which_key_ignore"}
  })
EOF
'''

# TODO 設定できたらやりたい
# [[plugins]]
# repo = 'kdheepak/lazygit.nvim'

